### ISSUE TITLE
Running brew as actual user instead of setup

### ISSUE THREAD

**Issue by sarcasticadmin** [Nebulaworks/tools-macos-init#2]
On my laptop it ran into an issue where `brew`'s directories were owned by `setup` instead of my actual user. Should we just run the brew installs as the user of the laptop?

**Comment by chrisciborowski** [comment]
comment in the script section says run as user, but also run script as priv. user. Modifying text to say run as standard user, should add a user check to code.

**Comment by sarcasticadmin** [comment]
closing as this seems something were less inlined to do with the rise of linux laptops for engineering
